branches:
    only:
        - master

language: node_js
script:
    - cd ./cliente-vue
    - npm install
after_sucess:
    - cd ..
    - openssl aes-256-cbc -K $encrypted_0ddd2445e49f_key -iv $encrypted_0ddd2445e49f_iv -in travis_rsa.enc -out travis_rsa -d
    - bash updateRepo.sh